### ISSUE TITLE
Xcode9.3.1，iPhone6s iOS11.3.1 报签名错误

### ISSUE THREAD

**Issue by yaoshenglong** [we11cheng/WCShadowrocket#2]
Code Signing Error: No account for team "296BA8G9JQ". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "296BA8G9JQ" with a private key was found.

**Comment by we11cheng** [comment]
我刚看了下，296BA8G9JQ 这个确实是我的项目teamID。配置自己的证书或者选择自己的team automatically manage signing 试试。

**Comment by yaoshenglong** [comment]
选择了自动配置证书，无论是公司的证书 还是我个人的证书都不行的，我感觉是项目里缺少了什么东西没上传。你把你的项目下载下来，换个证书试试，会不会出现证书问题。我的配置如下图：
![image](https://user-images.githubusercontent.com/13096573/40598607-497eb966-627b-11e8-8744-84638e3414bc.png)

**Comment by we11cheng** [comment]
两个target。动态库target 你看下

**Comment by we11cheng** [comment]
回复不是很及时。如果还是有问题的话。加下我微信或者qq。1396539283

**Comment by we11cheng** [comment]
更新了。拉下最新的代码试试。确实有坑

**Comment by yaoshenglong** [comment]
@we11cheng 新的代码运行OK， Niubility!!!
